name: Run Tests and Test Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: bun install --frozen-lockfile
      - name: Run tests
        run: bun test
      - name: Test build
        run: bun run build
